version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=postgres
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: bash -c "npx knex migrate:latest && npm run dev"
    restart: on-failure

  postgres:
    image: "postgres"
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    command: -p 5431
